export const tech = {
    Angular: "Angular",
    Bootstrap: "Bootstrap",
    Chai: "Chai",
    CSS3: "CSS3",
    D3: "D3",
    Docker: "Docker",
    Express: "Express",
    HTML5: "HTML5",
    Java: "Java",
    Javascript: "Javascript",
    MongoDB: "MongoDB",
    MySQL: "MySQL",
    Nodejs: "Nodejs",
    Python: "Python",
    React: "React",
    Sass: "Sass",
    SpringBoot: "SpringBoot",
    TypeScript: "TypeScript"
}